### PR TITLE
Design proposal for Pure Terraform infrastructure management

### PR DESCRIPTION
**Pull request by stepanstipl**
Adding a proposal for pure Terraform based infrastructure management.

The proposal should be discussed below in this PR before potentially merged in and then serve as a blueprint for implementation steps.

### CODE REVIEW

**Comment by mrtyler** [comment]
Thanks, Stepan, for: creating this repo, writing up this proposal, demonstrating what design docs could look like, and doing a spike of the implementation! A lot of useful things.

After seeing a demo of Stepan's spike and reviewing this doc and the code, the team has agreed not to pursue this strategy at this time. The key reasons are:
* The spike would need further development to attain feature parity with the existing gpii-infra + exekube solution
* The October release is approaching fast, and we have a lot to do to prepare for it.
* Hence, we prefer to keep our momentum on the existing gpii-infra + exekube solution rather than changing approaches now

I had a lot of real-time conversations about this proposal since the decision was time-sensitive (had we decided to change course, we would have wanted to do so ASAP), which sort of circumvented Stepan's design doc. In the interest of trying out Stepan's design doc procedure, as well as recording the rationale behind our decision, here are some additional details I noted from my chats with the team:

* It is true that Exekube is a young project with few releases and one developer. However:
   * If we hadn't adopted Exekube we would have written something similar ourselves -- much as Stepan's spike is something similar: a (more-or-less) self-contained Docker image that uses Terraform and the Helm provider to deploy a Kubernetes cluster, supporting infrastructure, and GPII components. Using Exekube instead of rolling our own gave us a head start on the migration to GCP.
   * Exekube has more releases and developers than a new pure Terraform version of gpii-infra :). The effect may be small, but we have already benefited from upstream bug fixes and feature additions.
* Terragrunt is an additional dependency, but it adds value.
   * In case anyone hasn't seen it, the [Terragrunt README](https://github.com/gruntwork-io/terragrunt) provides a general overview of the problems Terragrunt helps solve.
   * One state file per component means reduced blast radius in case of corruption
      * This [Charity Majors article](https://charity.wtf/2016/03/30/terraform-vpc-and-why-you-want-a-tfstate-file-per-env/) is the one I always think of (warning: some strong language :)) even though things are a little different in Terraform in 2018.
      * @stepanstipl indicated that he thinks this is an anti-pattern. Stepan, can you elaborate?
   * Ties together multiple components with [dependencies](https://github.com/gruntwork-io/terragrunt#dependencies-between-modules)
      * @natarajaya has experience with this problem and how the Terragrunt solution compares with the pure Terraform solution. Sergey, can you elaborate?
         * It sounded like @stepanstipl has experience with the "module B references something in module A, so B ends up with an implicit dependency on A" workaround (which I thought we discovered somewhere in https://github.com/hashicorp/terraform/issues/10462 but I can't find it now). I know we talked about it but I'm not sure how much we explored it since we chose the Terragrunt solution instead.
* ruby/rake are additional dependencies, but they add value
   * I agree with pushing as much logic as possible down to Terraform, even when this means Terraform with small amounts of in-line bash. Exekube does that a fair bit and we have followed that approach where we thought it made sense, both to keep the rake layer as small as possible and so that gpii-infra behaves as much as possible like a "standard" exekube project.
   * This is a qualitative judgement, but I find make pretty obtuse. It can be difficult to search for the meaning of make constructions like `?=`, or the difference between `awk` and `@awk`.

I think there are lots of good and desirable goals here: simplify as much as possible, minimize dependencies / number of tools as much as possible, a self-contained gpii-infra Docker image, etc. Perhaps we can revisit this topic after the October release, at which time we'll all have more experience with the current gpii-infra + exekube approach and can better assess its strengths and weaknesses while we move into the next phase of the project.

**Comment by stepanstipl** [comment]
Thank Tyler for the detailed comment. We discussed this quite a bit, I would just add brief comments on some points mentioned, for the record.

- **Feature parity** - it's a spike, developed by one person in less than a week -> I don't think that missing feature parity is a fair argument in this context. Btw in some aspects, it has richer functionality than current code (bringing whole GCP org under management, secure config of Kube cluster, unique IDs for a project and clean project destroy to mention few).

- **Stepan's spike is something similar** - differences - completely contained docker, less many dependencies, simpler code. While it achieves similar goal, the design of this solution is different.
  - this is a spike -> no history
  - to compare complexity
     - current: 4k loc in 115 directories and 295 files
       (TF code - 882 loc, ruby (& Rake & erb) - 1397 loc, 115 directories and 295 files, Exekube's TF code - 1261 loc, Exekube's go - 179 loc)
     - spike - 626 loc in 11 directories and 36 files
        (TF code - 529 lines, Makefile - 97 lines, 36 files in 11 directories)

  While this is also not fair, given a different feature set, I believe it shows the trend. *Benefiting from upstream* - atm. we had to fork Exekube and also create our own docker image of it.

- **Terragrunt** -  what problems does it solve for us? Charity mentioned state per env. (I agree with that), as opposed to multiple state files per env (our case).
  - *Anti pattern* - TF does a good job on optimizing execution by building DAG based on dependencies, while Terragrun just *dumbly* executes TF on individual modules, which results in slow (in some cases significantly) execution. (I haven't seen a TF state corruption in quite a long time, but more states certainly mens more chances for corruption, no? :))

- *Ruby, rake* - I would argue that it might be a good tool for Ruby projects, but not in this case - the majority of our code is just executing shell with commands like curl, jq & kubectl. Writing this directly in bash or some simple tool is imho beneficial. 
  - *make* - while not defending make as having awesome syntax, it's de-facto standard (and lightweight one). (ruby & its deps are heavyweight - alpine image with make - 4.13MB, alpine image with Ruby, rake & bundler - 61.5MB). When you do simple things -> use simple tools.

As when and whether to reassess the decision - we are already in process of migrating from AWS to GCP, so I think it's a good time now. More unlikely to change anything in future, after investing another 3 months. I believe we would immediately benefit from simplified code and it would allow us to focus on developing features and things that need to be done, vs. fighting issues caused by many dependencies and unnecessarily complicated code.

Having said that, as the decision has been made, I'm closing this PR. But please continue to comment, I'm happy to continue the discussion.

**Comment by natarajaya** [comment]
@stepanstipl There is not much to add to what Tyler said in his comment, but let me try:
* I disagree that Terraform does better job handling dependencies, from my experience plain Terraform dependency management is way too complicated and requires number of [non-trivial hacks](https://github.com/stepanstipl/gpii-pure/blob/master/modules/demo/variables.tf). There are [corner cases](https://github.com/hashicorp/terraform/issues/10462) that simply can not be solved with plain TF.
* I also disagree that Terragrunt "just dumbly executes TF on individual modules". While Terragrunt dependecies are being [extremely straightforward](https://github.com/gpii-ops/gpii-infra/blob/master/gcp/live/dev/k8s/gpii/flowmanager/terraform.tfvars#L7), it also builds dependency graphs same way Terraform does, and applies multiple modules simultaneously if they have no blocking dependencies.
* Having separate tfstate per environment per module has great advantages, which I really appreciated dealing with "non-destructible" resources like KMS keys (another issue that is pretty hard to solve with pure TF).
* `Rakefile` vs `Makefile` choice does not make much difference to me. There will always be some glue code that needs to be placed somewhere and I am fine with any of them. I agree with Tyler that `make` syntax can be sometimes confusing (tabs vs spaces, etc). I can also say dealing with conditions, loops, files, different data structures is much easier with `ruby` than with pure `bash`. `Rake` has number of other advantages that we currently use (prerequisites and rules).  
* I am not aware of any issues "caused by many dependencies and unnecessarily complicated code" on GCP part of the project atm. In fact, I think our current GCP architecture will allow us to avoid this kind of issues in future! I hope once you get some more experience with it, you'll start to like it and appreciate some of the design choices as well! :)

**Comment by stepanstipl** [comment]
@natarajaya thanks for comments.
- Dependencies - pure TF does actually require you to declare those dependencies. Usually when it requires too many hacks, something is wrong with the design.

- Example:
  - resource a in module X - takes 15m to provision
  - resource b in module Y - takes 15m to provision
  - resource c in module Y - depends on X.a, takes 1m to provision

  Doing this pure TF way and declaring property of  X.a as output of module A and making Y.c depend 
  on it via  input variable, you get `X.a` and `Y.b` provisioned in parallel with `Y.c` provisioned 
  afterwards,  **whole run takes cca. 16m**.

  Doing this Terragrant way, declaring module X has to go before Y, you get `X.a` and `Y.b` 
  provisioned in sequence, **whole run will take 30m**.

  That's what I mean by "dump" Terragrunt.

- Whould you care to elaborate on what are actually the benefits of having separate TF states?

What is issue or not is obviously opinionated, but for me things like: dependencies on host (curl incompatibility issue), having to maintain our fork and own docker image of Exekube, secret's management leaking secrets (I know this is in progress, but the last iteration was), inability to cleanly destroy projects atm., mixing resource creation with Ruby code calling gcloud and Terraform, Exekube's insecure Kubernetes cluster config, and similar, are issues. Basically I believe in using simplest tool available (within reason) to do the job and not re-inventing the wheel.

**Pull request closed without merging**
